### ISSUE TITLE
General fixes from official scripts to import into unofficial scripts

### ISSUE THREAD

**Issue by ClementLouis** [ProjectIgnis/CardScripts#107]
- [x] Additional Normal Summon Bug: https://github.com/kevinlul/edopro-script/issues/11 (see pull https://github.com/kevinlul/edopro-script/pull/34 )
- [x] Must Attack Update: https://github.com/kevinlul/edopro-script/issues/1 -see pull https://github.com/kevinlul/edopro-script/pull/33 )
- [x] Trap that re-Set themselves: https://github.com/kevinlul/edopro-script/issues/20 (see pull https://github.com/kevinlul/edopro-script/pull/35 )
- [x]  Witchcrafter Genie: https://github.com/kevinlul/edopro-script/issues/49 idk if there is anime card with a similar effect, should be checked
- [x] Monster Gate/Iblee : https://github.com/kevinlul/edopro-script/issues/46 (depend on if the solution is validated)
- [x] Activation from the deck fix : https://github.com/kevinlul/edopro-script/pull/36
- [x] Quickplay activated turn set workaround removal
- [x] Linksummon() workaround removal
- [x] Continuous Trap rework (see https://github.com/kevinlul/edopro-script/pull/31 )
- [x] Dark Sacrifice vs Cards/Effect that negate and destroy (see https://github.com/kevinlul/edopro-script/issues/50)
- [x] Verify if cards need to have their link filters updates (see https://github.com/kevinlul/edopro-script/issues/79)
- [x] Verify if cards need to have their fusion material filters updates
- [ ] Verify if cards can use the fusion summon procedure : this is ydke url for cards that need to be checked`ydke://yHh1HtLo9QWdRnUevXh1HkV8dR6CSXUeQGZ+Hsl4dR7RR3Ue!!!` Last update: **14-Aug-2020**
- [ ] Master Rule 2020 GetLocationCountFromEx (see https://github.com/ProjectIgnis/CardScripts/issues/213)

**Comment by kevinlul** [comment]
Added `Master Rule 2020 GetLocationCountFromEx` since most unofficial cards don't work properly under Master Rule 2020.

**Comment by NaimSantos** [comment]
` Quickplay activated turn set workaround removal:`

I made a search by cards that mention "Quick-Spell" in their text than looked for the ones that allow them to be activated in the turn they are set and only found **Reservation Reward**, which has been changed in https://github.com/ProjectIgnis/CardScripts/commit/5212b562c27ad197b357450c2d6f6f173e2a3120, so I'm marking it as done.

**Comment by larry126** [comment]
Additional Normal Summon and re-Set Trap are done
Searched "Special Summon monsters, except" in unofficial DB, no result, marking "Monster Gate/Iblee" as done too

**Comment by larry126** [comment]
Added Card.IsDestructable check for unofficial cards

**Comment by larry126** [comment]
Continuous Trap rework done in https://github.com/ProjectIgnis/CardScripts/pull/257

**Comment by larry126** [comment]
"Verify if cards need to have their link filters updates" done in https://github.com/ProjectIgnis/CardScripts/commit/c158618fe451302d69e913b51f673e97050a5a89

**Comment by larry126** [comment]
"Activation from the deck fix" done in https://github.com/ProjectIgnis/CardScripts/commit/5360c52a86cfc8c78a532e3c8d11f40b30359889
