### ISSUE TITLE
Update Guidelines and Tasks

### ISSUE THREAD

**Issue by NaimSantos** [ProjectIgnis/CardScripts#24]
## Bugs 

- [x] Linkuriboh is incorrect at the moment, and can use any monster as material. The problem is related with the `FilterBoolFunctionEx `function.
- [x] Some fusion monsters are not working and cannot be summoned, due to the same `FilterBoolFunctionEx `function. Noted by me: Chaos Ancient Gear Giant, Prankids Battle Butter, the Dragon Maid fusion monster
- [x] Trackback Lancer returns script errors due to the removal of this function: `GetFreeLinkedZone`
- [x] Similarly, [all these cards here ](https://github.com/kevinlul/edopro-script/search?q=GetFreeLinkedZone&unscoped_q=GetFreeLinkedZone) use `GetFreeLinkedZone`
- [x] Lunalight Kaleido Chicken, even after sucessfuly sending the monster to the GY, cannot be used as that monster's name for a fusion summon.
- [x] Cards like "Code Talker" need to be updated due to Link Spells being available now, like "Judgement Arrows".
- [x] Update all cards that interact with the Extra deck to shuffle it after a reveal. Edopro has "Due.ShuffleExtra".
- [x]  Catalyst Field and similar cards with continuous effects that decrease the number of tributes required to summon other monsters are bugged, as seen in [this puzzle.](https://github.com/kevinlul/edopro-deploy/blob/master/puzzles/Puzzle%20to%20test%20Edopro/Test%20Catalyst%20Field.lua)
- [x] Fusion Spells need to be manually updated due to edo's change.
- [x] All Continuous Trap cards that have an effect that **can** be used when the card is flipped face-up need to be updated, as stated in #15.
- [ ] Persistent Trap cards need to be updated. See #15
- [x] Collection of bugs to investigate and fix #18 

In addition, all the [issues listed here](https://github.com/kevinlul/edopro-script/issues?q=is%3Aopen+is%3Aissue+label%3Abug) should be solved. These have puzzles available in the latest Edopro build, so you can test them.
## Enhancements:
All the following issues
- [x] #3 Use aux.FilterFaceupFunction. This one has been partially done by me, Naim
- [x] #4 Use SelectUnselect
- [x] #5 Use Card.IsHasLevel 
- [x] #6 Update listed_counters
- [x] #8  Revendread Origin and Nekroz Mirror
- [x] #7  GetMetatable update
- [ ] #2 Card names in scripts
- [x] #16 Add Mischief of the Time Goddess

 
## Before the release:

- [x] Verify GOAT Banlist.
- [x] Verify anime banlist due to the alias.
- [x] Test how live updates will work with the new banlist system.
- [x] Add missing field spell pictures to the repository where it gets them from.
- [x] Test the deck exporting feature.
- [x] Update puzzles to use the new message system.
- [x] Test Action Duels.
- [x] Test Speed Duels.
- [x] Test other duel modes.
- [x] Update the Readme.
- [x] Update the Changelog.

## Major script differences:

1. Counters: Any card that mentions a type of counter in the text must include the `s.counter_list` table. Cards that, specifically, place counters (either on themselves or others) will have the `s.counter_place_list`, instead. [See details in this discussion](https://github.com/kevinlul/edopro-script/pull/88#issuecomment-561140953)

2. `Duel.SpecialSummonStep` has been changed, and due to that, `SpecialSummonComplete`  must be moved out of that loop. [See how to do it here](https://github.com/kevinlul/edopro-script/pull/109/files)

3. Cards that have a filter with only 2 functions, where 1 of those are `IsFaceup` must use `aux.FilterFaceupFunction`. [See discussion and examples here](https://github.com/kevinlul/edopro-script/issues/3)

4. [Use "for" instead of "while" when iterating through a group](https://github.com/kevinlul/edopro-script/pull/116/files
)

5. Cards that had a filter with a single check + `IsFaceup` have been updated to use `aux.FilterFaceupFunction` instead, as seen in #3 

6. All Fusion Summon effects have been rewritten, due to changes in the Fusion Procedure. See #30, #26, also many changes made by Edo, but that are no longer in the commit history.

7. Ritual Effects have been changed, due to changes in the Ritual Summon Procedure.

8. The syntax for recipes that use `FilterBoolFunction` must be changed when the function passed takes more than 1 check, due to the usage of `FilterBoolFunctionEx`. Compare the script of Dragonmaid Husky with Percy's to see the difference.

9. The auxiliary function `SelectUnselect` has been applied to cards that could use it, to make a selection for cards matching a criteria cancelable, as seen in #4.

10. `Due.ShuffleExtra` has been applied to cards that reveal the Extra Deck

11. All the Continuous Traps have been changed, removing their complex handling for when it is possible to activate them, only, and activate and use their effects. See #31

12. Cards that have an Special Summon procedure that does some kind of selection - tributing, discarding, banishing, etc- must be changed to make such procedure cancelable. See examples in #90

13. Cards with effects that Fusion Summon should have the 'manual' approach for that effect, where you script it from the target to the operation function replaced by the Fusion Summon procedure. See examples in #160.

14
